application:
  logo: JuiceShopCTF_Logo.png
  favicon: favicon_ctf.ico
  showChallengeHints: false
  showVersionNumber: false
  gitHubRibbon: false
ctf:
  showFlagsInNotifications: true
  ctfdHost: http://10.20.33.101:8000
